### ISSUE TITLE
Allow extnding of inventory

### ISSUE THREAD

**Issue by zeezabug** [Vagabottos/root-rpg#91]
Allow extension of the inventory so you can see details of the items, similar to the plus buttons on the abilities tab. 

<img width="725" alt="Screen Shot 2022-07-25 at 7 51 08 PM" src="https://user-images.githubusercontent.com/109948278/180726110-07ce64e7-cd3a-4d63-ac73-0df67f5ea15f.png">

**Comment by seiyria** [comment]
This is a known bug.

**Comment by seiyria** [comment]
duplicate of #90
